name: Deploy Next.js to Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Install dependencies
        # حذف فایل Mirror برای جلوگیری از فریز شدن نصب
        run: |
          rm -f .npmrc
          npm install

      - name: Build with Next.js
        # اجبار به استفاده از Webpack به دلیل تنظیمات سفارشی در next.config.js
        run: npx next build --webpack

      - name: Fix Jekyll assets
        # جلوگیری از بلاک شدن پوشه _next توسط گیت‌هاب
        run: touch ./out/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
